DepressionApp/Models/Health.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DepressionApp.Models
{
	public class Health
	{
		[Key]
		public int ID { get; set; }
		//public string UserID { get; set; }
		public int Value { get; set; }
		public DateTime HealthDate { get; set; }

		public virtual User User { get; set; }
	}
}

DepressionApp/Models/Mood.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DepressionApp.Models
{
	public class Mood
	{
		[Key]
		public int ID { get; set; }
		//public string UserID { get; set; }
		public int Value { get; set; }
		public string Description { get; set; }
		public DateTime MoodDate { get; set; }

		public virtual User User { get; set; }

	}
}

DepressionApp/Models/Relax.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DepressionApp.Models
{
	public class Relax
	{
		[Key]
		public int ID { get; set; }
		//public string UserID { get; set; }
		public bool Value { get; set; }
		public DateTime RelaxDate { get; set; }

		public virtual User User { get; set; }
	}
}

DepressionApp/Controllers/ChartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DepressionApp.Models;
using System.Data;
using System.Data.Entity;
using System.Net;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace DepressionApp.Controllers
{
    public class ChartController : Controller
    {
        // GET: Chart
        [HttpPost]
        public ActionResult Index()
        {

            using (DepressionAppContext db = new DepressionAppContext())
            {
                var list1 = db.Moods.Select(x =>  x.Value).ToList().Distinct();

                var list2 = db.Moods.Select(x => x.MoodDate).ToList().Distinct(); ;

                ViewBag.ValuesArray = JsonConvert.SerializeObject(list1);
                ViewBag.DateArray = JsonConvert.SerializeObject(list2);
                return RedirectToAction("Analysis", "Home");

            }
        }
        } 
}

DepressionApp/Controllers/HealthController.cs
using DepressionApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DepressionApp.Controllers
{
    public class HealthController : Controller
    {
        // GET: Health
        public ActionResult Index()
        {
            return View();
        }

		[HttpPost]
		public ActionResult SaveHealth(DepressionApp.Models.Health health)
		{

			using (var context = new DepressionAppContext())
			{
				int id = (int)Session["ID"];
				User user = context.Users.Find(id);

				var healths = new List<Health>
					{
					new Health{Value=health.Value, HealthDate=DateTime.Today, User=user}
				};

				healths.ForEach(s => context.Healths.Add(s));
				context.SaveChanges();

			}
			return RedirectToAction("Index", "Home");
		}
	}
}

DepressionApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text.Encodings.Web;

namespace DepressionApp.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}

		public ActionResult Mood()
		{
			ViewBag.Message = "Your application description page.";

			return View();
		}
		public ActionResult Health()
		{
			ViewBag.Message = "Your application description page.";

			return View();
		}
		public ActionResult Relax()
		{
			ViewBag.Message = "Your application description page.";

			return View();
		}

		public ActionResult Contact()
		{
			ViewBag.Message = "Your contact page.";

			return View();
		}
		public ActionResult Login()
		{
			ViewBag.Message = "Your contact page.";

			return View();
		}
		public ActionResult Register()
		{
			return View();
		}
		public ActionResult Analysis()
		{
			return View();
		}

		
		public ActionResult Animation()
		{
			return View();
		}
		//public ActionResult User()
		//{
		//	ViewBag.Message = "Your contact page.";

		//	return View();
		//}

		public string Welcome(string name, int numTimes = 1)
		{
			return HtmlEncoder.Default.Encode($"Hello {name}, NumTimes is: {numTimes}");
		}
	}
}

DepressionApp/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DepressionApp.Models;
using System.Data;
using System.Data.Entity;
using System.Net;
//using DepressionApp.DAL;


namespace DepressionApp.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
		{

			//using (DepressionAppContext db = new DepressionAppContext())
			//{
			//	var users = new List<User>
			//		{
			//		new User{Email="Carson",Password="Alexander"},
			//		new User{Email="Meredith",Password="Alonso"},
			//		new User{Email="Arturo",Password="Anand"},
			//		new User{Email="Gytis",Password="Barzdukas"},
			//		new User{Email="Yan",Password="Li"},
			//		new User{Email="Peggy",Password="Justice"},
			//		new User{Email="Laura",Password="Norman"},
			//		new User{Email="Nino",Password="Olivetto"}
			//		};

			//	db.Users.Add(users[0]);
			//	db.SaveChanges();
			//}

				return View();
        }

        [HttpPost]
        public ActionResult Autherize(DepressionApp.Models.User userModel)
        {
            using (DepressionAppContext db = new DepressionAppContext())
            {
				userModel.Password = Crypto.Hash(userModel.Password);
				var userDetails = db.Users.Where(x => x.Email == userModel.Email && x.Password == userModel.Password).FirstOrDefault();
                if (userDetails == null)
                {
                    userModel.LoginErrorMessage = "Wrong username or password.";
                    return View("Index", userModel);
                    
                }
                else
                {
                    Session["ID"] = userDetails.ID;
                    Session["Email"] = userDetails.Email;
                    return RedirectToAction( "Index", "Home");
                }
            }
        }

        public ActionResult LogOut()
        {
			if (Session["ID"]!=null)
			{
				int userId = (int)Session["ID"];
				Session.Abandon();
			}
            return RedirectToAction("Login", "Home");
        }
    }
}

DepressionApp/Controllers/MoodController.cs
using DepressionApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DepressionApp.Controllers
{
	public class MoodController : Controller
	{
		// GET: Mood
		public ActionResult Index()
		{
			return View();
		}

		
		public ActionResult SaveMood()
		{
			return View();
		}

		[HttpPost]
		public ActionResult SaveMood(DepressionApp.Models.Mood mood)
		{
			
			using (var context = new DepressionAppContext())
			{
				int id = (int)Session["ID"];
				User user = context.Users.Find(id);

				var moods = new List<Mood>
					{
					new Mood{Value=mood.Value,Description=mood.Description,MoodDate=DateTime.Today, User=user}
				};

				moods.ForEach(s => context.Moods.Add(s));
				context.SaveChanges();

			} 

			//return View("Mood", "Home");
			return RedirectToAction("Index", "Home");
		}
	}
}

DepressionApp/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
//using DepressionApp.DAL;
using DepressionApp.Models;
using System.Net.Mail;

namespace DepressionApp.Controllers
{ // http://www.entityframeworktutorial.net/code-first/simple-code-first-example.aspx
	public class UserController : Controller
	{
		private DepressionAppContext db = null;//= new DepressionAppContext();


		// GET: User
		public ActionResult Index()
		{


			using (var context = new DepressionAppContext())
			{

				var users = new List<User>
					{
					new User{Email="Carson",Password="Alexander"},
					new User{Email="Meredith",Password="Alonso"},
					new User{Email="Arturo",Password="Anand"},
					new User{Email="Gytis",Password="Barzdukas"},
					new User{Email="Yan",Password="Li"},
					new User{Email="Peggy",Password="Justice"},
					new User{Email="Laura",Password="Norman"},
					new User{Email="Nino",Password="Olivetto"}
					};

				users.ForEach(s => context.Users.Add(s));
				context.SaveChanges();

			} // żeby to odpalić do adresu dodać /User/Index
			return View();// db.Users.ToList());
		}

		// GET: User/Details/5
		public ActionResult Details(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			User user = db.Users.Find(id);
			if (user == null)
			{
				return HttpNotFound();
			}
			return View(user);
		}

		// GET: User/Create
		public ActionResult Create()
		{
			return View();
		}

		// POST: User/Create
		// Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
		// Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create([Bind(Include = "ID,Email,Password")] User user)
		{
			if (ModelState.IsValid)
			{
				db.Users.Add(user);
				db.SaveChanges();
				return RedirectToAction("Index");
			}

			return View(user);
		}

		// GET: User/Edit/5
		public ActionResult Edit(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			User user = db.Users.Find(id);
			if (user == null)
			{
				return HttpNotFound();
			}
			return View(user);
		}

		// POST: User/Edit/5
		// Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
		// Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit([Bind(Include = "ID,Email,Password")] User user)
		{
			if (ModelState.IsValid)
			{
				db.Entry(user).State = EntityState.Modified;
				db.SaveChanges();
				return RedirectToAction("Index");
			}
			return View(user);
		}

		// GET: User/Delete/5
		public ActionResult Delete(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			User user = db.Users.Find(id);
			if (user == null)
			{
				return HttpNotFound();
			}
			return View(user);
		}

		// POST: User/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public ActionResult DeleteConfirmed(int id)
		{
			User user = db.Users.Find(id);
			db.Users.Remove(user);
			db.SaveChanges();
			return RedirectToAction("Index");
		}

		//protected override void Dispose(bool disposing)
		//{
		//	if (disposing)
		//	{
		//		db.Dispose();
		//	}
		//	base.Dispose(disposing);
		//}
        [NonAction]
        public bool IsEmailExist(string emailID)
        {
            using (DepressionAppContext dc = new DepressionAppContext())
            {
                var v = dc.Users.Where(a => a.Email == emailID).FirstOrDefault();
                return v != null;
            }
        }
        public ActionResult Register()
        {
            return View();
        }

        //[NonAction]
        //public void SendVerificationLinkEmail(string emailID, string activationCode)
        //{
        //    var verifyUrl = "/User/VerifyAccount/" + activationCode;
        //    var link = Request.Url.AbsoluteUri.Replace(Request.Url.PathAndQuery, verifyUrl);

        //    var fromEmail = new MailAddress("dotnetawesome@gmail.com", "Dotnet Awesome");
        //    var toEmail = new MailAddress(emailID);
        //    var fromEmailPassword = ""; //haslo
        //    string subject = "Your account is successfully created!";

        //    string body = "<br/><br/>We are excited to tell you that your Dotnet Awesome account is" +
        //        " successfully created. Please click on the below link to verify your account" +
        //        " <br/><br/><a href='" + link + "'>" + link + "</a> ";

        //    var smtp = new SmtpClient
        //    {
        //        Host = "smtp.gmail.com",
        //        Port = 587,
        //        EnableSsl = true,
        //        DeliveryMethod = SmtpDeliveryMethod.Network,
        //        UseDefaultCredentials = false,
        //        Credentials = new NetworkCredential(fromEmail.Address, fromEmailPassword)
        //    };

        //    using (var message = new MailMessage(fromEmail, toEmail)
        //    {
        //        Subject = subject,
        //        Body = body,
        //        IsBodyHtml = true
        //    })
        //        smtp.Send(message);
        //}

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Register([Bind(Exclude = "IsEmailVerified,ActivationCode")] User user)
        {
            bool Status = false;
            string message = "";
            //
            // Model Validation 
            if (ModelState.IsValid)
            {

                #region //Email is already Exist 
                var isExist = IsEmailExist(user.Email);
                if (isExist)
                {
                    ModelState.AddModelError("EmailExist", "Email already exist");
                    return View(user);
                }
                #endregion

                #region Generate Activation Code 
                user.ActivationCode = Guid.NewGuid();
                #endregion

                #region  Password Hashing 
                user.Password = Crypto.Hash(user.Password);
                user.ConfirmPassword = Crypto.Hash(user.ConfirmPassword); //
                #endregion
                user.Isverificated = false;

                #region Save to Database
                using (DepressionAppContext dc = new DepressionAppContext())
                {
                    dc.Users.Add(user);
                    dc.SaveChanges();

                    //Send Email to User
                    //SendVerificationLinkEmail(user.Email, user.ActivationCode.ToString());
                    //message = "Registration successfully done. Account activation link " +
                    //    " has been sent to your email id:" + user.Email;
                    //Status = true;
                }
                #endregion
            }
            else
            {
                message = "Invalid Request";
            }

            ViewBag.Message = message;
            ViewBag.Status = Status;

			return RedirectToAction("Index", "Home");

		}


    }
}

DepressionApp/Views/Home/Analysis.cshtml
@{
    ViewBag.Title = "Analysis";
    if (Session["ID"] == null)
    {
        Response.Redirect("~/Home/Login");
    }
}

<style>
 .login-page {
        width: 600px;
        padding: 8% 0 0;
       margin: auto;
    }

    .form {
        position: relative;
        z-index: 1;
        background: #FFFFFF;
        max-width: 600px;
        margin: 0 auto 100px;
        padding: 45px;
        text-align: center;
        box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
    }
    
        .form input {
            font-family: "Roboto", sans-serif;
            outline: 0;
            background: #f2f2f2;
            width: 100%;
            border: 0;
            margin: 0 0 15px;
            padding: 15px;
            box-sizing: border-box;
            font-size: 14px;
        }

        .form button {
            font-family: "Roboto", sans-serif;
            text-transform: uppercase;
            outline: 0;
            background: #EB8E98;
            width: 100%;
            border: 0;
            padding: 15px;
            color: #FFFFFF;
            font-size: 14px;
            -webkit-transition: all 0.3 ease;
            transition: all 0.3 ease;
            cursor: pointer;
        }

            .form button:hover, .form button:active, .form button:focus {
                background: #FEE2D7;
            }

        .form .message {
            margin: 15px 0 0;
            color: #b3b3b3;
            font-size: 12px;
        }

            .form .message a {
                color: #65725E;
                text-decoration: none;
            }

        .form .register-form {
            display: none;
        }

    .container {
        position: relative;
        z-index: 1;
        max-width: 500px;
        margin: 0 auto;
    }

        .container:before, .container:after {
            content: "";
            display: block;
            clear: both;
        }

        .container .info {
            margin: 50px auto;
            text-align: center;
        }

            .container .info h1 {
                margin: 0 0 15px;
                padding: 0;
                font-size: 36px;
                font-weight: 300;
                color: #1a1a1a;
            }

            .container .info span {
                color: #4d4d4d;
                font-size: 12px;
            }

                .container .info span a {
                    color: #000000;
                    text-decoration: none;
                }

                .container .info span .fa {
                    color: #FEE2D7;
                }

    body {
        background: #FEE2D7; /* fallback for old browsers */
        background: -webkit-linear-gradient(right, #FEE2D7);
        background: -moz-linear-gradient(right, #FEE2D7);
        background: -o-linear-gradient(right, #FEE2D7);
        background: linear-gradient(to left, #FEE2D7);
        font-family: "Roboto", sans-serif;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
    }

</style>
<script src="~/Scripts/Chart.min.js"></script>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery-3.3.1.js"></script>
<script src="~/Scripts/jquery-3.3.1.slim.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.2.2/Chart.bundle.min.js"></script>  
<script>
    //var ValueArray =;
    //var DateArray =;

    
   
    var config = {

            type:'line',   
            data: {
                labels: [ @Html.Raw(Json.Encode(ViewBag.DateArray))],
                datasets: [{
                    label: "Your Data",
                    backgroundColor: [
                        "#f990a7",
                        "#aad2ed",
                        "#9966FF",
                        "#99e5e5",
                        "#f7bd83",
                    ],
                    data: [ @Html.Raw(Json.Encode(ViewBag.ValuesArray))]}], 
               
        },
    options: {
            responsive: true,
            title: {
            display: true,
            text: 'Chart with your data'
            }},
           
            scales: {
                    xAxes: [{
                        display: true,
                        scaleLabel: {
                            display: true,
                            labelString: 'Month'
                        }
                    }]},
                    yAxes: [{
                        display: true,
                        scaleLabel: {
                            display: true,
                            labelString: 'Value'
                        }
                    }]
            };
        
    //    options: {
    //        maintainAspecRaito:false,
    //        scales:{yAxes:[{ticks:{beginAtZero:true}}]},
    //        legend: {display:false}
    //    }
    //}
    window.onload = function() {
        var ctx = $("#my_chart").get(0).getContext("2d");
       //var ctx = document.getElementById('canvas').getContext('my_chart');
        window.myLine = new Chart(ctx, config);
    };
   
    
</script>
<h2><center>Analysis</center></h2>
@using (Html.BeginForm("Index", "Chart", FormMethod.Get)) { 
<div class="login-page">

    <div class="form">

        
            <canvas id="my_chart">
               
            </canvas>

        

    </div>
</div>}

DepressionApp/Views/Home/Login.cshtml
@model DepressionApp.Models.User


<style>


    .login-page {
        width: 360px;
        padding: 8% 0 0;
        margin: auto;
    }

    .form {
        position: relative;
        z-index: 1;
        background: #FFFFFF;
        max-width: 360px;
        margin: 0 auto 100px;
        padding: 45px;
        text-align: center;
        box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
    }

        .form input {
            font-family: "Roboto", sans-serif;
            outline: 0;
            background: #f2f2f2;
            width: 100%;
            border: 0;
            margin: 0 0 15px;
            padding: 15px;
            box-sizing: border-box;
            font-size: 14px;
        }

        .form button {
            font-family: "Roboto", sans-serif;
            text-transform: uppercase;
            outline: 0;
            background: #EB8E98;
            width: 100%;
            border: 0;
            padding: 15px;
            color: #FFFFFF;
            font-size: 14px;
            -webkit-transition: all 0.3 ease;
            transition: all 0.3 ease;
            cursor: pointer;
        }

            .form button:hover, .form button:active, .form button:focus {
                background: #FEE2D7;
            }

        .form .message {
            margin: 15px 0 0;
            color: #b3b3b3;
            font-size: 12px;
        }

            .form .message a {
                color: #65725E;
                text-decoration: none;
            }

        .form .register-form {
            display: none;
        }

    .container {
        position: relative;
        z-index: 1;
        max-width: 500px;
        margin: 0 auto;
    }

        .container:before, .container:after {
            content: "";
            display: block;
            clear: both;
        }

        .container .info {
            margin: 50px auto;
            text-align: center;
        }

            .container .info h1 {
                margin: 0 0 15px;
                padding: 0;
                font-size: 36px;
                font-weight: 300;
                color: #1a1a1a;
            }

            .container .info span {
                color: #4d4d4d;
                font-size: 12px;
            }

                .container .info span a {
                    color: #000000;
                    text-decoration: none;
                }

                .container .info span .fa {
                    color: #FEE2D7;
                }

    body {
        background: #FEE2D7; /* fallback for old browsers */
        background: -webkit-linear-gradient(right, #FEE2D7);
        background: -moz-linear-gradient(right, #FEE2D7);
        background: -o-linear-gradient(right, #FEE2D7);
        background: linear-gradient(to left, #FEE2D7);
        font-family: "Roboto", sans-serif;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
    }
</style>
<script>
    $('.message a').click(function () {
        $('form').animate({ height: "toggle", opacity: "toggle" }, "slow");
    });
</script>


<h2><center>Login</center></h2>
<div class="login-page">

    <div class="form">
        <form class="register-form">
            <input type="text" placeholder="name" />
            <input type="password" placeholder="password" />
            <input type="text" placeholder="email address" />
            <button>create</button>
            <p class="message">Already registered? <a href="#">Sign In</a></p>
        </form>
@using (Html.BeginForm("Autherize", "Login", FormMethod.Post))
{
        <form class="login-form">
            @Html.LabelFor(model => model.Email)
            @Html.EditorFor(model => model.Email) 
            @Html.ValidationMessageFor(model => model.Email)
            <p></p>
            @Html.LabelFor(model => model.Password)
            @Html.EditorFor(model => model.Password)
            @Html.ValidationMessageFor(model => model.Password)
            <button>login</button>
            <p class="message">Not registered? @Html.ActionLink("Create an account", "Register","User")</p>
            @Html.DisplayFor(model => model.LoginErrorMessage)
        </form>
}
    </div>
</div>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

DepressionApp/Views/Home/RegisterEx.cshtml
@{
    ViewBag.Title = "Register";
}

<h2><center>Register</center></h2>

@model DepressionApp.Models.User


<style>
    .login-page {
        width: 360px;
        padding: 8% 0 0;
        margin: auto;
    }

    .form {
        position: relative;
        z-index: 1;
        background: #FFFFFF;
        max-width: 360px;
        margin: 0 auto 100px;
        padding: 45px;
        text-align: center;
        box-shadow: 0 0 20px 0 rgba(0, 0, 0, 0.2), 0 5px 5px 0 rgba(0, 0, 0, 0.24);
    }

        .form input {
            font-family: "Roboto", sans-serif;
            outline: 0;
            background: #f2f2f2;
            width: 100%;
            border: 0;
            margin: 0 0 15px;
            padding: 15px;
            box-sizing: border-box;
            font-size: 14px;
        }

        .form button {
            font-family: "Roboto", sans-serif;
            text-transform: uppercase;
            outline: 0;
            background: #EB8E98;
            width: 100%;
            border: 0;
            padding: 15px;
            color: #FFFFFF;
            font-size: 14px;
            -webkit-transition: all 0.3 ease;
            transition: all 0.3 ease;
            cursor: pointer;
        }

            .form button:hover, .form button:active, .form button:focus {
                background: #FEE2D7;
            }

        .form .message {
            margin: 15px 0 0;
            color: #b3b3b3;
            font-size: 12px;
        }

            .form .message a {
                color: #65725E;
                text-decoration: none;
            }

        .form .register-form {
            display: none;
        }

    .container {
        position: relative;
        z-index: 1;
        max-width: 500px;
        margin: 0 auto;
    }

        .container:before, .container:after {
            content: "";
            display: block;
            clear: both;
        }

        .container .info {
            margin: 50px auto;
            text-align: center;
        }

            .container .info h1 {
                margin: 0 0 15px;
                padding: 0;
                font-size: 36px;
                font-weight: 300;
                color: #1a1a1a;
            }

            .container .info span {
                color: #4d4d4d;
                font-size: 12px;
            }

                .container .info span a {
                    color: #000000;
                    text-decoration: none;
                }

                .container .info span .fa {
                    color: #FEE2D7;
                }

    body {
        background: #FEE2D7; /* fallback for old browsers */
        background: -webkit-linear-gradient(right, #FEE2D7);
        background: -moz-linear-gradient(right, #FEE2D7);
        background: -o-linear-gradient(right, #FEE2D7);
        background: linear-gradient(to left, #FEE2D7);
        font-family: "Roboto", sans-serif;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
    }
</style>
<script>
    $('.message a').click(function () {
        $('form').animate({ height: "toggle", opacity: "toggle" }, "slow");
    });
</script>


    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    

<div class="form">
    <form class="register-form">
        <input type="text" placeholder="name" />
        <input type="password" placeholder="password" />
        <input type="text" placeholder="email address" />
        <button>create</button>
        <p class="message">Already registered? <a href="#">Sign In</a></p>
    </form>
    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })

    <div class="login-form">
        @using (Html.BeginForm("Register","User", FormMethod.Post))
        {
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            @Html.ValidationMessage("EmailExist", new { @class = "text-danger" })

            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })

            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })


            <input type="submit" value="Create" class="btn btn-default" />
            <p class="message">Already registered? @Html.ActionLink("Sing In", "Login") </p>
        }
        </div>

</div>
        </div>
    </div>

    @section Scripts{
        <script src="~/Scripts/jquery.validate.min.js"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    }